"""The task queue: durable, leased, and a directory of files.

A file per task, and an atomic rename to publish each change. That is the whole
storage design, and it is a deliberate answer to the brief's instruction not to
add infrastructure that measured workload does not justify.

What a queue has to do here is hold tens of tasks, survive a process dying, and
let one control plane hand work to a handful of workers. A directory does all
three. What a broker would add is throughput this workload does not have, and a
service to run, secure, back up and upgrade. ``docs/platform.md`` records the
measurement.

What this is not
----------------

It is not safe for two control planes writing at once. There is no lock across
processes, so concurrent leasing from two control-plane instances can hand one
task to two workers. That is the point at which a real database earns its place,
and the limitation is stated rather than hidden behind hopeful language.
"""

from __future__ import annotations

import os
import tempfile
from datetime import timedelta
from pathlib import Path

from pydantic import ValidationError

from devforge.core.errors import DevForgeError
from devforge.core.models import utcnow
from devforge.platform.models import (
    Lease,
    TaskEnvelope,
    TaskRecord,
    TaskState,
    WorkerIdentity,
)

QUEUE_DIRNAME = "queue"
#: How long a worker holds a task before it returns to the queue. Long enough for
#: a slow task, short enough that a worker that died is not a task lost forever.
DEFAULT_LEASE_S = 1_800


class TaskQueue:
    """Tasks on disk, one JSON file each, newest state wins."""

    def __init__(self, root: Path) -> None:
        self.root = Path(root)
        self.directory = self.root / ".devforge" / "platform" / QUEUE_DIRNAME
        self.directory.mkdir(parents=True, exist_ok=True)

    # -- storage ----------------------------------------------------------------

    def path_for(self, task_id: str) -> Path:
        # The id is generated by `new_id`, but it also arrives from a peer over
        # the protocol, so it is validated rather than trusted.
        if not task_id or "/" in task_id or "\\" in task_id or ".." in task_id:
            raise DevForgeError(f"'{task_id}' is not a task id")
        return self.directory / f"{task_id}.json"

    def save(self, record: TaskRecord) -> Path:
        record.touch()
        path = self.path_for(record.task_id)
        _atomic_write(path, record.model_dump_json(indent=1))
        return path

    def load(self, task_id: str) -> TaskRecord:
        path = self.path_for(task_id)
        try:
            return TaskRecord.model_validate_json(path.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise DevForgeError(f"no task '{task_id}' in the queue") from exc
        except (OSError, ValidationError) as exc:
            raise DevForgeError(f"could not read task '{task_id}': {exc}") from exc

    def all(self) -> list[TaskRecord]:
        records: list[TaskRecord] = []
        for path in sorted(self.directory.glob("*.json")):
            try:
                records.append(TaskRecord.model_validate_json(path.read_text(encoding="utf-8")))
            except (OSError, ValidationError):
                # One unreadable file must not hide the rest of the queue. It is
                # surfaced by `unreadable()` rather than swallowed here.
                continue
        return sorted(records, key=lambda record: record.envelope.submitted_at)

    def unreadable(self) -> list[str]:
        """Files in the queue directory that will not parse. Reported, not ignored."""
        broken: list[str] = []
        for path in sorted(self.directory.glob("*.json")):
            try:
                TaskRecord.model_validate_json(path.read_text(encoding="utf-8"))
            except (OSError, ValidationError):
                broken.append(path.name)
        return broken

    # -- lifecycle --------------------------------------------------------------

    def submit(self, envelope: TaskEnvelope) -> TaskRecord:
        record = TaskRecord(envelope=envelope, state=TaskState.QUEUED)
        self.save(record)
        return record

    def ready(self) -> list[TaskRecord]:
        """Tasks a worker could take now, oldest first.

        Expiring a stale lease happens here rather than on a timer: the only
        moment the answer matters is when somebody asks what is available, and a
        background sweeper would be a second thing that can fail.
        """
        available: list[TaskRecord] = []
        for record in self.all():
            if record.state is TaskState.LEASED and record.lease and record.lease.expired():
                self._expire(record)
            if record.state is TaskState.QUEUED:
                available.append(record)
        return available

    def _expire(self, record: TaskRecord) -> None:
        record.lease = None
        record.reason = "the lease expired before the worker returned a result"
        if record.attempts >= record.envelope.max_attempts:
            record.state = TaskState.EXPIRED
        else:
            record.state = TaskState.QUEUED
        self.save(record)

    def lease(
        self,
        identity: WorkerIdentity,
        record: TaskRecord,
        *,
        seconds: int = DEFAULT_LEASE_S,
    ) -> Lease:
        if record.state is not TaskState.QUEUED:
            raise DevForgeError(
                f"task '{record.task_id}' is {record.state.value}, not queued"
            )
        lease = Lease(
            task_id=record.task_id,
            worker_id=identity.worker_id,
            expires_at=utcnow() + timedelta(seconds=seconds),
        )
        record.lease = lease
        record.state = TaskState.LEASED
        record.attempts += 1
        self.save(record)
        return lease

    def check_lease(self, record: TaskRecord, worker_id: str) -> None:
        """A result is only accepted from the worker that actually holds the lease.

        Without this, any registered worker could return a result for any task -
        authentication proves who is speaking, not what they were asked to do.
        """
        if record.lease is None:
            raise DevForgeError(f"task '{record.task_id}' is not leased to anyone")
        if record.lease.worker_id != worker_id:
            raise DevForgeError(
                f"task '{record.task_id}' is leased to '{record.lease.worker_id}', "
                f"not to '{worker_id}'"
            )
        if record.lease.expired():
            raise DevForgeError(
                f"the lease on '{record.task_id}' expired at "
                f"{record.lease.expires_at.isoformat()}"
            )

    def counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for record in self.all():
            counts[record.state.value] = counts.get(record.state.value, 0) + 1
        return counts


def _atomic_write(path: Path, text: str) -> None:
    """Write a whole file or none of it.

    A half-written task file is worse than a missing one: it parses as a
    different task, or fails to parse and takes its record with it.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(text)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
